### ISSUE TITLE
Not working for sub-generators

### ISSUE THREAD

**Issue by alexlafroscia** [boneskull/create-yo#11]
It seems like sub-generators are interpreted as a URL scheme, so the command fails to run correctly.

```
$ npm init yo generator:subgenerator eslint-config
✖ create-yo errored:

Error: Unsupported URL Type "generator:": generator:subgenerator
```

The same happened when trying to run `create-yo` through `yarn create` as well.

Running directly through `npx` did work, however

```
$ npx -p generator-generator -p yo -- yo generator:subgenerator eslint-config
   create generators/eslint-config/index.js
   create generators/eslint-config/templates/dummyfile.txt
   create __tests__/eslint-config.js
```

**Comment by boneskull** [comment]
This should be fixed in [v2.0.0](https://github.com/boneskull/create-yo/commit/53595c98efcd7c26c5d27fb57f583d6539be9eaa)
