### ISSUE TITLE
command not found: yo

### ISSUE THREAD

**Issue by Meligy** [boneskull/create-yo#2]
Hello,
Thanks a lot for the great effort with this. From the code it looks like you really tried hard to cover many cases.

Unfortunately when I run this though, I get an error:

```
npm init yo express
npx: installed 128 in 6.422s
npx: installed 412 in 13.06s
npx: command not found: yo
```

I'm running Node v11.3.0 and npm v6.5.0 if that helps, but I don't expect anything really changed in eother to block this awesome script. I don't know.

Any thoughts?

Thanks again.

**Comment by boneskull** [comment]
Can you provide more information on your environment?

Also, v1.1.2 should be released momentarily, and you may have better luck with that.

**Comment by boneskull** [comment]
closed for inactivity

**Comment by Meligy** [comment]
Yes. It's working with latest version. Sorry for not responding earlier.
